version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout

      - run:
          name: Install Maven
          command: |
            sudo apt update
            sudo apt install -y maven

      - run:
          name: Run Selenium Tests
          command: mvn test

workflows:
  version: 2
  run-tests:
    jobs:
      - test
