version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0  # or 11.0, depending on your Java version
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn install -DskipTests
      - run:
          name: Run Selenium Tests
          command: mvn test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
